// scripts/analyze-demo.mjs
// 데모 mp3를 분석해 src/example/exampleData.generated.ts 를 생성한다.
// 실행: node scripts/analyze-demo.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { MPEGDecoder } from "mpg123-decoder";
import {
  spectralFluxEnvelope, peakPick, estimateBpm, quantize, dedupeSorted, routeOnsets,
} from "./analysisCore.mjs";

const SAMPLES = ["kick", "snare", "hat", "clap", "tom", "perc"];
const BANDS = {
  low: { loHz: 20, hiHz: 150 },
  mid: { loHz: 150, hiHz: 2000 },
  high: { loHz: 4000, hiHz: 16000 },
};
const MIN_GAP_MS = 90;      // 트랙당 최소 마커 간격
const MAX_PER_TRACK = 240;  // 과밀 방지 상한

const dec = new MPEGDecoder();
await dec.ready;
const mp3 = readFileSync("public/samples/moodmode-demo.mp3");
const { channelData, samplesDecoded, sampleRate } = dec.decode(mp3);
dec.free();

// 모노 믹스다운
const mono = new Float32Array(samplesDecoded);
const chs = channelData.length;
for (let i = 0; i < samplesDecoded; i++) {
  let s = 0;
  for (let c = 0; c < chs; c++) s += channelData[c][i];
  mono[i] = s / chs;
}
const durationMs = Math.round((samplesDecoded / sampleRate) * 1000);

// 대역별 온셋(ms)
const bandPeaks = {};
let bpmEnv = null, bpmHop = null;
for (const [band, { loHz, hiHz }] of Object.entries(BANDS)) {
  const { env, hopSec } = spectralFluxEnvelope(mono, sampleRate, { fftSize: 1024, hop: 512, loHz, hiHz });
  if (band === "mid") { bpmEnv = env; bpmHop = hopSec; }
  const minGapFrames = Math.max(1, Math.round(MIN_GAP_MS / 1000 / hopSec));
  const idx = peakPick(env, { window: 16, multiplier: 1.4, minGap: minGapFrames });
  bandPeaks[band] = idx.map((i) => i * hopSec * 1000);
}

// 템포 → 16분 그리드 양자화
const bpm = Math.round(estimateBpm(bpmEnv, bpmHop, { min: 90, max: 160 }));
const beatMs = 60000 / bpm;
const sixteenth = beatMs / 4;
const phaseMs = bandPeaks.low[0] ?? bandPeaks.mid[0] ?? 0;
for (const band of Object.keys(bandPeaks)) {
  bandPeaks[band] = dedupeSorted(quantize(bandPeaks[band], sixteenth, phaseMs), MIN_GAP_MS)
    .filter((t) => t >= 0 && t <= durationMs);
}

// 6트랙 라우팅 + 밀도 상한
const routed = routeOnsets(bandPeaks, beatMs, phaseMs);
for (const k of SAMPLES) {
  routed[k] = dedupeSorted(routed[k], MIN_GAP_MS).slice(0, MAX_PER_TRACK).map((t) => Math.round(t));
}

// 생성 파일 작성
const lines = SAMPLES.map((k) => `  ${k}: [${routed[k].join(", ")}],`).join("\n");
const body = `// AUTO-GENERATED by scripts/analyze-demo.mjs. Do not edit by hand.
// 재생성: node scripts/analyze-demo.mjs
export const EXAMPLE_DURATION_MS = ${durationMs};
export const EXAMPLE_BPM = ${bpm};
export const EXAMPLE_TRACK_MARKERS: Record<string, number[]> = {
${lines}
};
`;
mkdirSync("src/example", { recursive: true });
writeFileSync("src/example/exampleData.generated.ts", body);
console.log(`bpm=${bpm} durationMs=${durationMs}`);
for (const k of SAMPLES) console.log(`  ${k}: ${routed[k].length} markers`);
